controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    use_sim_time: true  # Use real-time instead of simulation time
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    ur_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    rg2_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

ur_arm_controller:
  ros__parameters:
    use_sim_time: true  # Use real-time instead of simulation time
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true  # Use real-time instead of simulation time

gz_ros2_control:
  ros__parameters:
    position_proportional_gain: 1.0   # try 0.8–1.0 for grippers

rg2_trajectory_controller:
  ros__parameters:
    joints: [rg2_finger_joint1, rg2_finger_joint2]
    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]
    allow_partial_joints_goal: false
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01